# Generated by Django 5.2.1 on 2025-05-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
