# Generated by Django 5.2.1 on 2025-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_vehicle_name_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_assigned',
            field=models.BooleanField(default=False, help_text='Indicates if a driver is assigned to this vehicle'),
        ),
    ]
